apiVersion: v1
kind: Service
metadata:
  name: dummy2-service
spec:
  selector:
    app: dummy2
  ports:
  - protocol: TCP
    port: 8080  # Specify the port to expose
    targetPort: 3434  # Specify the port your application listens on

# kubectl get pods --selector=app=prometheus -o=jsonpath='{.items[0].metadata.namespace}'
